# Generated by Django 5.1.1 on 2024-10-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
