# Generated by Django 5.1.1 on 2024-10-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
