# Generated by Django 5.1.1 on 2024-10-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
