# Generated by Django 5.1.1 on 2024-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0007_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
