# Generated by Django 5.1.1 on 2024-10-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
    ]
